export const MFA_CONFIG = {
  PENDING_COOKIE_NAME: "cfl_mfa",
  CHALLENGE_TTL_MS: 1000 * 60 * 10,
  EMAIL: {
    RESEND_INTERVAL_MS: 1000 * 60,
    MAX_ATTEMPTS: 5,
  },
  TOTP: {
    MAX_ATTEMPTS: 5,
    SECRET_BYTES: 20,
    PERIOD_SECONDS: 30,
    DIGITS: 6,
    ALGORITHM: "SHA1",
    WINDOW: 1,
    ENCRYPTION_VERSION: 1,
    ENCRYPTION_ALGORITHM: "aes-256-gcm",
    ISSUER: "Certfolio",
    BASE32_ALPHABET: "ABCDEFGHIJKLMNOPQRSTUVWXYZ234567",
  },
  RECOVERY_CODES: {
    COUNT: 10,
    SEGMENT_LENGTH: 4,
    ALPHABET: "ABCDEFGHJKLMNPQRSTUVWXYZ23456789",
  },
  TRUSTED_DEVICE: {
    COOKIE_NAME: "cfl_mfa_trusted",
    TTL_MS: 1000 * 60 * 60 * 24 * 30,
  },
} as const

export const RECENT_PASSWORD_CONFIRMATION_CONFIG = {
  TTL_MS: 1000 * 60 * 10,
} as const

export const RATE_LIMIT_CONFIG = {
  SIGN_UP: {
    IP_MAX_ATTEMPTS: 10,
    ACCOUNT_MAX_ATTEMPTS: 5,
    WINDOW_MS: 1000 * 60 * 15,
  },
  SIGN_IN: {
    IP_MAX_ATTEMPTS: 20,
    ACCOUNT_MAX_ATTEMPTS: 10,
    WINDOW_MS: 1000 * 60 * 15,
  },
  FORGOT_PASSWORD: {
    IP_MAX_ATTEMPTS: 10,
    ACCOUNT_MAX_ATTEMPTS: 5,
    WINDOW_MS: 1000 * 60 * 15,
  },
  EMAIL_VERIFICATION: {
    PENDING_COOKIE_NAME: "cfl_verify_email",
    PENDING_TTL_MS: 1000 * 60 * 15,
    IP_MAX_ATTEMPTS: 10,
    ACCOUNT_MAX_ATTEMPTS: 5,
    WINDOW_MS: 1000 * 60 * 15,
  },
  MFA: {
    IP_MAX_ATTEMPTS: 20,
    ACCOUNT_MAX_ATTEMPTS: 10,
    WINDOW_MS: 1000 * 60 * 15,
  },
} as const
